### ISSUE TITLE
Support for setting entry expiry at renewal

### ISSUE THREAD

**Issue by Hawxy** [jodydonetti/ZiggyCreatures.FusionCache#17]
Hello, I'm interested in adding FusionCache into one of my libraries as a replacement for LazyCache. However it's missing a feature I use from the base Microsoft cache abstractions, namely the ability to set the cache expiry dynamically at the time of entry renewal via the `ICacheEntry` interface like so:

```csharp
 await _cache.GetOrAddAsync("key", async e =>
            {            
                var response = await _client.GetRemoteItemAsync();     

                e.SetAbsoluteExpiration(response.Expiry);

                return response.Item;
            });        
 ```

This is super useful if you don't know the expiry of the item upfront. Are there any plans to support something like this?

**Comment by Hawxy** [comment]
Sounds good to me! Thanks.

**Comment by jodydonetti** [comment]
Hi @Hawxy ! I've finally find some time to put down in words a couple of proposals for this here #24 !
I would be really interesed in knowing what you think.
Thanks!

**Comment by Hawxy** [comment]
Sweet! I'll take a look when I get a moment.

**Comment by jodydonetti** [comment]
Closing as now there's a full fledged issue (#24) to track this development.
