### ISSUE TITLE
Question : How are cache invalidations handled?

### ISSUE THREAD

**Issue by MartyBJones** [jodydonetti/ZiggyCreatures.FusionCache#32]
Say I have a web application running on 4 servers that uses FusionCache with a Redis secondary cache and I remove a cache entry from one of the web applications.  It looks like the local FusionCache will be removed and the Redis secondary cache will have it's entry removed but how will the other 3 servers know to clear their FusionCache entries?

**Comment by jodydonetti** [comment]
Hi @MartyBJones , thanks for considering FusionCache.

The scenario you are talking about is an example of why I'm working on adding a backplane (see #11), which I hope will be available soon.
Btw you caught me working on it right at this very moment 😅

Another approach which would give similar results is to have a very low memory cache duration along with a higher distributed cache duration (like requested in #30) to highly reduce the differences between the memory and the distributed cache.

**Comment by MartyBJones** [comment]
The backplane sounds promising!   I look forward to trying it out!

**Comment by jodydonetti** [comment]
Hi @MartyBJones , I'm happy to say that I've finally been able to complete the design and implementation of the **backplane** feature.

Please take a look [here](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/releases/tag/v0.1.10-alpha1), try it out and let me know what you think so I can move forward with the final version.

Thanks 🙏

**Comment by MartyBJones** [comment]
That is great news!  I will try to look at it sometime next week.

**Comment by jodydonetti** [comment]
Meanwhile I published an (hopefully) even better [alpha2](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/releases/tag/v0.1.10-alpha2) release.

**Comment by jodydonetti** [comment]
Hi all, yesterday I released the [BETA 3](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/releases/tag/v0.1.10-beta3).

Unless some big problem comes up, this will be the very last release before the official one, which will be in the next few days 🎉

**Comment by jodydonetti** [comment]
Closing this since with [v0.9.0](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/releases/tag/v0.9.0) the backplane is an official feature, with [official docs](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/docs/Backplane.md) and more.

**Comment by MartyBJones** [comment]
Jody, have you don’t any performance metrics on the new backplane?  Just
wondering how many notifications it can handle.

**Comment by jodydonetti** [comment]
Hi @MartyBJones , there are no intrinsic limits on how many notifications it can handle, it wholly depends on the underlying pub/sub mechanism used.

For example using the common Redis implementation on, say, an Azure Redis Cache instance will be subjected to the limits of that infrastructure and the Redis internal limits themselves (some of which you can see [here](https://redis.io/docs/reference/clients/)).

In general I haven't found any particular bottlenecks or problems in general regarding the pub/sub part (which is what is used in the backplane), but I don't have precise number yet.
