### ISSUE TITLE
[Question] How factory call is synchronized between nodes?

### ISSUE THREAD

**Issue by Rast1234** [jodydonetti/ZiggyCreatures.FusionCache#50]
In the docs there's a `FactoryOptimization.md` which says

> Special care is put into calling just one factory per key, concurrently

Can you please provide more details on how this works?  I'm curious what happens within FusionCache when:

* we use SQL as storage
* there are more than 1 application node
* 2 or more nodes call GetOrSet with the same key concurrently
* factory is non-trivial, eg. takes time and can fail

Does FusionCache implement some sort of distributed lock on a given storage to synchronize nodes? For instance, some atomic operation is needed in SQL to create a "locking" row for a key, call factory and insert value, or remove lock if factory failed.

**Comment by jodydonetti** [comment]
ps: more generally FusionCache uses a form of mutex. In particular it is currently using a series of `SemaphoreSlim`s (one per key) to coordinate factory execution. Internally this synchronization mechanism is modeled with the `IFusionCacheReactor` interface, and it has different potential implementations (if interested you can find them in the `Reactors` folder) because that is an area I like to explore more, trying out different approaches. Btw since I consider this part experimental I'm not quite ready to have it accessible from the outside, so all classes are marked as `internal` for now. One of the other approaches I'm exploring that may be quite interesting is a _probabilistic_ one, based on some probabilty theory (eg: kinda like the reverse of the [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem)) but that's another story.

**Comment by Rast1234** [comment]
Thank you, that's surely **the** thing to mention in docs! You see, i've found this library: [IdempotentAPI](https://github.com/ikyriak/IdempotentAPI). It has an option to use FusionCache as a back-end. Since FusionCache doesn't guarantee single factory execution in multi-node environment, that lib does not truly implement idempotency...

Thing is, for caching that's mostly OK - when keys are rarely written and actively read. Jittering and other mitigations surely help a lot in this case, too. But if someone tries to protect data from being double-processed etc, this is not an option, because keys are usually short-lived and the whole point is to protect code from running twice when key is about to be inserted.

**Comment by jodydonetti** [comment]
I'll update the docs and mention more explicitly the distributed lock limitation, thanks!

> You see, i've found this library: [IdempotentAPI](https://github.com/ikyriak/IdempotentAPI). It has an option to use FusionCache as a back-end. Since FusionCache doesn't guarantee single factory execution in multi-node environment, that lib does not truly implement idempotency...

I've heard of IdempotentAPI but haven't had the time yet to carefully look into it.
My doubt is this: are you sure that the "guarantee idempotency" part is based on the caching layer itself? Maybe the caching layer is just that, a caching layer?

To understand it better I've contacted the author @ikyriak to see if they can chip in this discussion, will see what they say, fingers crossed 🤞

> Thing is, for caching that's mostly OK - when keys are rarely written and actively read. Jittering and other mitigations surely help a lot in this case, too. But if someone tries to protect data from being double-processed etc, this is not an option, because keys are usually short-lived and the whole point is to protect code from running twice when key is about to be inserted.

Yep, for caching that's ok, and Fusion**Cache** is a cache, so 😅

Anyway I'll try to look into how IdempotentAPI uses FusionCache and will let you know!

**Comment by jodydonetti** [comment]
Hey @Rast1234 I just took a quick look at IdempotentAPI, here's what I found.

There are 2 impl offered for the caching layer and, apart from the FusionCache one, the other is implemented on top of `IDistributedCache` ([here](https://github.com/ikyriak/IdempotentAPI/blob/master/src/IdempotentAPI.Cache.DistributedCache/IdempotencyDistributedCache.cs)).

From what I see that implementation does not use any distributed locking too, so I assume the part where it guarantees total idempotency including in a multi-node scenario is probably handled somewhere else. If that is the case, FusionCache is functionally the same, except with also a local cache, fail-safe, etc.

Or maybe I am missing something, what do you think?

**Comment by Rast1234** [comment]
Guessing from what i've seen in IdempotentAPI sources, when using FusionCache, it relies on it as synchronization point via GetOrSet, thus not locking multiple nodes. Worth mentioning in their docs too. I was hesitant to contact @ikyriak because i didn't dig into IDistributedCache thing yet...

**Comment by ikyriak** [comment]
Hello @Rast1234 & @jodydonetti,

I hope you are doing well.

You are right. The current implementations of `IIdempotencyCache` do not support distributed locks and thus, do not support idempotency in a cluster environment.

I'll update the `IdempotentAPI` docs regarding the cluster environment limitation. In addition, I have created a related [issue ](https://github.com/ikyriak/IdempotentAPI/issues/34) to implement the missing feature.

Thanks for taking the time to investigate the `IdempotentAPI`, and please do not hesitate to contact me 😄

**Comment by Rast1234** [comment]
I Just didn't have time to check other caching implementation :) Great, i guess this issue is solved then.

**Comment by jodydonetti** [comment]
Hi @ikyriak and thanks for answering!

**Comment by jodydonetti** [comment]
Hi @Rast1234 , I've updated [the docs](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/docs/CacheStampede.md) with additional notes about multiple nodes.
