### ISSUE TITLE
Minimum log level

### ISSUE THREAD

**Issue by angularsen** [jodydonetti/ZiggyCreatures.FusionCache#65]
**Is your feature request related to a problem? Please describe.**

Despite configuring all minimum log levels to `Error`, there are still lots of logs spamming my Serilog sinks with Debug level like these:

```
[12:03:15 DBG] FUSION (O=9ff57fa21f0b4df5968ceda1f0289538 K=MyKey): memory entry found FE[]
[12:03:15 DBG] FUSION (O=9ff57fa21f0b4df5968ceda1f0289538 K=MyKey): return FE[]
[12:03:15 DBG] FUSION (O=e4c2667cd74d49198de1f16e981e0484 K=MyKey): calling GetOrSetAsync<T> FEO[LKTO=/ DUR=06:00:00 JIT=0 PR=N FS=N FSMA
X=1.00:00:00 FSTHR=30s FSTO=0 FHTO=/ TOFC=Y DSTO=/ DHTO=/ ABDO=N BN=Y BBO=Y]
```

I would like to configure a minimum log level for FusionCache, in addition to the existing log level options for individual groups of logs.

**Describe the solution you'd like**
Add `FusionCacheOptions.MinimumLogLevel`, which controls the minimum log level. Defaults to Verbose.

**Describe alternatives you've considered**
Followed instructions in https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/docs/StepByStep.md#9-logging.
Explored all configurable options, could not find any.

Workaround is to configure Serilog to set a minimun log level override for these loggers.
```cs
.MinimumLevel.Override("ZiggyCreatures.Caching.Fusion.FusionCache", LogEventLevel.Information)
```

**Comment by angularsen** [comment]
I agree with some of your points, but I would propose a few counter arguments:
- You already provide options for controlling some log levels, so configuring a minimum log level is something at least I would expect to find there.
- Out of the box, the library is quite spammy. I would expect out of the box to get the most essential, informative messages, like cache updated, fetching value from distributed cache, errors in the factory etc. Debug level events like fail-safe mode activation and very internal diagnostic messages is something I expect to be turned off by default. It just makes it a lot easier to add the library and not having to tweak log messages for a "comfortable" level of logging. It's excellent that you can turn it up to 11 if you need to debug though.

I have my workaround, so if you want to close this issue I'm fine with that.

**Comment by jodydonetti** [comment]
I've researched some more for best practices and similar and found this for example [Logging in C# .NET Modern-day Practices: The Complete Guide](https://michaelscodingspot.com/logging-in-dotnet/).

In section "2. Enable only high-severity logs in Production" it says _"As a rule of thumb, we don’t want to enable Debug and Info levels in production. We want to log just Warn messages and above or just Error and above. The reason is better performance, avoid using more storage and possibly avoid sending sensitive information."_ which was my point.

I'll research a bit more but it seems to me this is the correct approach.

**Comment by angularsen** [comment]
We do restrict to `Information` level in deployed environments, so this issue is more about the developer experience when running locally. 

FusionCache dominated our logs because we have `Verbose` as minimum log level when running our services locally, in order to get detailed application logs. This means we have to filter library logs, like FusionCache. It works, it's really not a big problem, but it is just another thing you have to configure for every library that supports logging. 

Maybe this is controversial, I'm not sure, but if instead the library defaulted to `Information` level out of the box, I think it would better match developers' expectations. More detailed logs could be enabled by configuration. I can't speak for everyone, but that is what I would expect.


This is our current filtering setup, so Microsoft's own libraries are also quite spammy:
```cs
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning) // Too many events per API/MVC call, replaced by Serilog.AspNetCore.
                .MinimumLevel.Override("Microsoft.Hosting.Lifetime", LogEventLevel.Information) // Startup logs like "Now listening on: http://localhost:5000"
                .MinimumLevel.Override("Microsoft.EntityFrameworkCore", LogEventLevel.Warning) // Limit to warning to not log every "Executed DbCommand".
                .MinimumLevel.Override("IdentityServer4.EntityFramework.TokenCleanup", LogEventLevel.Warning) // Mute token cleanup, every 30 minutes for our IdentityServer instances.
                .MinimumLevel.Override("Microsoft.ApplicationInsights.Profiler", LogEventLevel.Warning) // Mute profiler log events related to profiler sessions that are started all the time.
                .MinimumLevel.Override("System.Net.Http.HttpClient", LogEventLevel.Warning) // Mute default HttpClient log spam, we use our own request logger
                .MinimumLevel.Override("System", LogEventLevel.Information)
```

**Comment by jodydonetti** [comment]
> We do restrict to Information level in deployed environments, so this issue is more about the developer experience when running locally.

Oh I did not get that you were talking about local development, now it's clearer thanks!

> This is our current filtering setup, so Microsoft's own libraries are also quite spammy

Eh, that is what I was thinking at to be honest, in trying to align with the expectations one may get from the framework itself.

I'll keep this issue open since it's a subject I'd like to deepen a little bit more.
Maybe I'll launch a tweet to see what people came up with.

Thanks!

**Comment by jodydonetti** [comment]
For reference: [tweet](https://twitter.com/jodydonetti/status/1550822778860871681) posted.

**Comment by jodydonetti** [comment]
Update: the most common consensus seems to be that the current approach is the correct (and expected) one, so I'm closing this issue for now.

I remain ofcourse committed to discuss this again in the future if new evidence will emerge that may change the rationale.

Thanks for participating!

**Comment by angularsen** [comment]
Thanks for entertaining the idea and making the effort to investigate, I
agree this probably is the best practice for libraries.

**Comment by jodydonetti** [comment]
Hi @angularsen , I've created the Logging docs [here](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/docs/Logging.md): if you have time let me know what you think.

Thanks!

**Comment by angularsen** [comment]
@jodydonetti I can only applaude the effort you put into documentation 👏 It is really good and was one of the things that convinced me to try FusionCache in the first place. It is across the board excellent, the logging docs too.

A couple of things that may help improve the logging docs:
- Start the article with a short "getting started": Short snippets of code for the most common approaches to configure logging, probably DI or manually. My take is that this is what most are looking for. The thorough introduction to logging in .NET is great, but might be redundant for developers already familiar with logging in general.
- Recommended dev vs. prod log settings, you touch on it, but a section dedicated to how you typically want to configure logging for development vs production is always helpful as a starting point. For example, we are currently limiting all FusionCache logs to Information, although it seems it is mostly VRB/DBG or WRN/ERR and very few Info level messages so far in our logs.
- Using events to add custom logs. I believe I saw this elsewhere in the docs, but it seemed to me like a nice way to improve logging.

**Comment by jodydonetti** [comment]
Hi @angularsen

> @jodydonetti I can only applaude the effort you put into documentation 👏 It is really good and was one of the things that convinced me to try FusionCache in the first place. It is across the board excellent, the logging docs too.

Thanks, I really appreciate your words 🙏

> A couple of things that may help improve the logging docs:
> 
> * Start the article with a short "getting started": Short snippets of code for the most common approaches to configure logging, probably DI or manually. My take is that this is what most are looking for. The thorough introduction to logging in .NET is great, but might be redundant for developers already familiar with logging in general.

I totally agree with you and I even tried that, but the problem I've faced was that the code to setup and/or configure a logger depended on what logger is being used, because the built-in native loggers are not so used in my opinion, and people generally use either Serilog, NLog or Log4Net.

Would you add code snippets only for the native loggers or for one of the others, too?

Don't you feel that maybe adding a code sample for the native ones may guide newbies towards thme, like _"ok I'll just copy-paste this and move on"_ removing the exploration phase with different, more powerful loggers (think structured logging, etc)?

I'd like to know your opinion on this.

> * Recommended dev vs. prod log settings, you touch on it, but a section dedicated to how you typically want to configure logging for development vs production is always helpful as a starting point.

Great point, I'll work on this!

> * Using events to add custom logs. I believe I saw this elsewhere in the docs, but it seemed to me like a nice way to improve logging.

Ah that's a nice idea, something like _"normally fail-safe activations are logged, but if you want to log with a custom log level in case of fail-safe activations for a particular piece of data here's how to do that"_ and then show how to subscribe to fail-safe activations events and send a custom log message.
Nice idea, will do!

**Comment by jodydonetti** [comment]
Hi @angularsen , I've updated the Logging docs, please let me know what you think.
Thanks!

**Comment by angularsen** [comment]
Great!
A few initial thoughts:


https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/Logging.md#di-dependency-injection
In this section, I would throw in `AddFusionCache()` next to where logging is configured, so it is more obvious how the two are configured together. In addition to the link to DI docs.

```cs
// Configure logging and enable services to get ILogger<T> injected.
services.AddLogging(b => b
    .SetMinimumLevel(LogLevel.Information) // Global minimum log level.
    .AddSimpleConsole()                    // Write to console.
);

// Add FusionCache and optionally override its default options.
services.AddFusionCache(options => {
	options.CacheName = "MyCache";
	options.DistributedCacheErrorsLogLevel = LogLevel.Warning;
	// ...and more.
});
```

### Production & Performance Considerations
https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/Logging.md#-production--performance-considerations

- Typo: "As we saw we can log a lot of information~~s~~"
- Next to dev/prod suggestions, link back to how to configure minimum log level: https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/Logging.md#-standard-configuration
- I personally found `Information` level to be what I wanted in both local and dev/prod environments, although I don't think I've ever seen an Information level event. Only Debug or Warn/Error. Debug is way too verbose for me, but since we use [Seq](https://datalust.co/seq) to display and filter local logs, we can stream Debug level logs there and filter on Information in Seq. This makes it easy to dive into Debug level logs whenever we need it, and filter to the relevant app instances and code, without having to re-run the apps with new log config. I don't know if this is something to include in the docs or not, maybe as a tip to consider using Seq and other log tools instead of just console output.

**Comment by angularsen** [comment]
@jodydonetti 
Great!
A few initial thoughts:


https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/Logging.md#di-dependency-injection
In this section, I would throw in `AddFusionCache()` next to where logging is configured, so it is more obvious how the two are configured together. In addition to the link to DI docs.

```cs
// Configure logging and enable services to get ILogger<T> injected.
services.AddLogging(b => b
    .SetMinimumLevel(LogLevel.Information) // Global minimum log level.
    .AddSimpleConsole()                    // Write to console.
);

// Add FusionCache and optionally override its default options.
services.AddFusionCache(options => {
	options.CacheName = "MyCache";
	options.DistributedCacheErrorsLogLevel = LogLevel.Warning;
	// ...and more.
});
```

### Production & Performance Considerations
https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/Logging.md#-production--performance-considerations

- Typo: "As we saw we can log a lot of information~~s~~"
- Next to dev/prod suggestions, link back to how to configure minimum log level: https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/Logging.md#-standard-configuration
- I personally found `Information` level to be what I wanted in both local and dev/prod environments, although I don't think I've ever seen an Information level event. Only Debug or Warn/Error. Debug is way too verbose for me, but since we use [Seq](https://datalust.co/seq) to display and filter local logs, we can stream Debug level logs there and filter on Information in Seq. This makes it easy to dive into Debug level logs whenever we need it, and filter to the relevant app instances and code, without having to re-run the apps with new log config. I don't know if this is something to include in the docs or not, maybe as a tip to consider using Seq and other log tools instead of just console output.

**Comment by jodydonetti** [comment]
> https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/Logging.md#di-dependency-injection
> In this section, I would throw in `AddFusionCache()` next to where logging is configured, so it is more obvious how the two are configured together. In addition to the link to DI docs.
> 
> ```cs
> // Configure logging and enable services to get ILogger<T> injected.
> services.AddLogging(b => b
>     .SetMinimumLevel(LogLevel.Information) // Global minimum log level.
>     .AddSimpleConsole()                    // Write to console.
> );
> 
> // Add FusionCache and optionally override its default options.
> services.AddFusionCache(options => {
> 	options.CacheName = "MyCache";
> 	options.DistributedCacheErrorsLogLevel = LogLevel.Warning;
> 	// ...and more.
> });
> ```

Makes sense, I've added it.

I just removed the `options.DistributedCacheErrorsLogLevel = LogLevel.Warning` part since at this point I haven't yet touched on that, and I don't want to let readers confused about it, but I added it later on.

> * Typo: "As we saw we can log a lot of information~s~"

Thanks, fixed!

> * Next to dev/prod suggestions, link back to how to configure minimum log level: https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/Logging.md#-standard-configuration

Will do, thanks.

> * I personally found `Information` level to be what I wanted in both local and dev/prod environments

You are right, but I was talking about logging in general, not strictly related to FusionCache. But this is kind of the "problem" about this specific doc page: it tries to mix a generic logging intro with logging specific to FusionCache. I think there's a value to such a document, but at the same time I see where the confusion may arise.
I'll try to make it clear, thanks for spotting it.

> although I don't think I've ever seen an Information level event. Only Debug or Warn/Error

I am thinking about changing a couple of log levels to `Information`, like the high-level method calls `GetOrSet` which, in the context on the library itself, are in fact "high-level" operations.

I always had the doubt though about which level to use, because on one hand they are high-level in the context of the lib, but on the other hand such a level may be misplaced for such a thing.

What do you think about it?

**Comment by angularsen** [comment]
I think once we filtered out Debug level log events locally, we are seeing a satisfactory amount of log events both during development and in production.

I'm not really missing anything, I generally want FusionCache to stay quiet while it is operating as intended. It is particularly when Redis or the value factory is having issues that it starts spewing warnings and errors, which I do like.

So far I don't have any particular requests on log level changes, but I'll report back if we stumble on some.
