### ISSUE TITLE
Different duration in distributed cache

### ISSUE THREAD

**Issue by angularsen** [jodydonetti/ZiggyCreatures.FusionCache#66]
We have two sources of data, primary and secondary.

- If primary is fetched, we want to 
  - Renew local cache after 6 hours (Duration=6h)
  - Reuse local value up to 24 hours if problems. (FailSafeMaxDuration=24h)
  - Expire distributed cache after 24 hours, instead of 6 hours. ❓ 
- If primary fails and secondary is fetched, we want to 
  - Renew local cache immediately (Duration=0s + some throttling)
  - Reuse local value up to 24 hours if problems. (FailSafeMaxDuration=24h)
  - Expire distributed cache after 24 hours, instead of immediately. ❓ 

❓ How can we configure distributed cache to a different value than the local cache?

Also, setting `Duration = TimeSpan.Zero` results in an exception for distributed cache, which would be solved by setting distributed cache duration differently:
```
System.ArgumentOutOfRangeException: The absolute expiration value must be in the future. (Parameter 'AbsoluteExpiration')
Actual value was 04.07.2022 12:17:49 +00:00.
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAbsoluteExpiration(DateTimeOffset creationTime, DistributedCacheEntryOptions options)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.SetAsync(String key, Byte[] value, DistributedCacheEntryOptions options, CancellationToken token)
   at ZiggyCreatures.Caching.Fusion.Internals.Distributed.DistributedCacheAccessor.<>c__DisplayClass15_0`1.<<SetEntryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ZiggyCreatures.Caching.Fusion.Internals.FusionCacheExecutionUtils.RunAsyncActionAdvancedAsync(Func`2 asyncAction, TimeSpan timeout, Boolean cancelIfTimeout, Boolean awaitCompletion, Action`1 exceptionProcessor, Boolean reThrow, CancellationToken token)
```

**Comment by jodydonetti** [comment]
Hi @angularsen , changing some options (like `Duration`) based on which datasource has succeeded fetching is possible thanks to [Adaptive Caching](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/docs/AdaptiveCaching.md): I can imagine something like a try/catch block with the primary loading logic, and then another one for the secondary that would change the duration in case of success.

Using different durations between memory and distributed is not **currently** possible: havign said that, it's something I'm currently exploring thanks to a [a request from the comunity](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/discussions/60), just like yours!

If you like, please participate in that discussion, I will update as soon as there's something available.

**Comment by jodydonetti** [comment]
Oh, I almost forgot: regarding the zero duration I would suggest trying to use something very small like `TimeSpan.FromMilliseconds(50)` or something like that which in practice should give you the same effect.

**Comment by angularsen** [comment]
Thanks @jodydonetti, I'm sure this is a useful feature. However, In my case, I had really just misunderstood how the cache lifetime configuration of FusionCache worked. 

I thought `Duration` set the expiration, but with fail-safe enabled, it really is `FailSafeMaxDuration` that controls the cache time to live in both memcache + Redis. 

Some suggestions to xmldocs summaries:

**Duration**
Before:
```
The amount of time after which a cache entry is considered expired.
```

After:
```
If <see cref="IsFailSafeEnabled" /> is <c>true</c>, <see cref="Duration"> describes when the cache is considered stale and should be renewed, while <see cref="FailSafeMaxDuration" /> describes when the cache expires and is no longer available.<br />
If <see cref="IsFailSafeEnabled" /> is <c>false</c>, <see cref="Duration"> describes when the cache expires and is no longer available.
```

**FailSafeMaxDuration**
Before:
```
When fail-safe is enabled an entry will expire normally nonetheless, but it will also be kept around for this (usually long) duration, so it may be used as a fallback value in case of errors. TL/DR: the maximum amount of time a cache entry can be used, even if expired, in case of problems.`
```

After:
```
If <see cref="IsFailSafeEnabled" /> is <c>true</c>, <see cref="Duration"> describes when the cache is considered stale and should be renewed, while <see cref="FailSafeMaxDuration" /> describes when the cache expires and is no longer available.<br />
If <see cref="IsFailSafeEnabled" /> is <c>false</c>, this config has no effect.
```

Also, I think the terms used by CacheTower is more intuitive, where you configure `timeToLive` and `staleAfter`.

I posted about it here just now:
https://github.com/ZiggyCreatures/FusionCache/discussions/60#discussioncomment-3440963

**Comment by jodydonetti** [comment]
Thanks @angularsen , I'll try to update the xml docs to be more clear.

One small thing though: as you pointed out it currently says _"The amount of time after which a cache entry is CONSIDERED expired"_, it doesn't say _"... after which a cache entry WILL EXPIRE"_. My rational was that in choosing those words I was trying to comprise both scenario, with and without fail-safe enabled.

Now that you point that out though, maybe that was a little too nitpicky so a more clear approach may be better, even more so considering some users will just be "outside" users, like people simply using the lib and looking at the fine details, not maintaining the caching infrastructure (eg: the Redis instance, the Memcached instance, etc) while other users will do that too, so there's value in being more explicit about the inner details.

Will think about this and update you, thanks for the suggestion!

**Comment by angularsen** [comment]
@jodydonetti Sorry for late reply, thanks Jody for your great efforts on docs and improvements!

We're using FusionCache more and more in our backend since we first started experimenting with different caching libraries back in July and it has worked great for us so far 🙇

**Comment by jodydonetti** [comment]
Thanks, I'm happy about that!
