### ISSUE TITLE
Fail-safe getting or setting featuring a default value

### ISSUE THREAD

**Issue by clxx** [jodydonetti/ZiggyCreatures.FusionCache#8]
Hi, if the cache is initally empty, even a fail-safe `GetOrSet` still throws an exception, since there is no expired value for the key which can be retrieved. There is a `GetOrDefault`, but from the otherwise excellent documentation and the example code alone it is not clear, how to combine these features. Is that really some kind of missing method (like a `GetOrSetOrDefault` feature or an overload with a default value) or is this by design? Either way, it would be awesome if this case is mentioned. Thank you very much!

**Comment by jodydonetti** [comment]
Hi, thanks for trying out FusionCache!

> Hi, if the cache is initally empty, even a fail-safe `GetOrSet` still throws an exception, since there is no expired value for the key which can be retrieved.

Correct: `GetOrSet` means _"get me the value and, if not there, call this factory"_.

To be more precise, if the factory then throws an exception, then:
- if fail-safe is enabled **and** there's an expired value -> it will be cached again for some time (`FailSafeThrottleDuration`) and returned
- if fail-safe is disabled **or** there's no expired value -> the exception will bubble up and you'll have to handle it

> There is a `GetOrDefault`, but from the otherwise excellent documentation and the example code alone it is not clear, how to combine these features. Is that really some kind of missing method (like a `GetOrSetOrDefault` feature or an overload with a default value) or is this by design? Either way, it would be awesome if this case is mentioned. Thank you very much!

Well first of all thank you, it's nice to know you enjoyed the documentation, I tried hard to make it as clear as possible.

Secondly, I think you have a point here but I would like to know if I'm getting it right.

What you would like to have is a `GetOrSet` method that basically works like now but also, in case the factory throws an exception (or times out if there are timeous set) **and** there's no expired value to fallback to, may return a default value?

Did I get it right?

If that is the case, may I ask if you would expect it to just return the default value without caching it (like the `GetOrDefault` method does) or to cache it (like the `GetOrSet` method does)?

**Comment by clxx** [comment]
Hi,

> Did I get it right?

**Yes, that's exactly what I mean!**

> If that is the case, may I ask if you would expect it to just return the default value without caching it (like the `GetOrDefault` method does) or to cache it (like the `GetOrSet` method does)?

I see two main usages, each on it's own right:

_**Firstly**_, having an **initial** value as if a previous call of the factory method would have returned it, to bridge the time until the first real result is ready in case of initial problems. Mostly, this initial value would be a somewhat meaningless empty collection, string, default value etc., just to prevent `NullReferenceException`s, so it wouldn't make sense to cache it with the same duration as a real factory result - and if that _would_ make any sense, one could try/catch/query timeout directly in the factory callback.

Such an initial value could be treated best like a just expired entry, otherwise either with the same options as any later result from the factory, or - even better - with it's own configurable options.

From my point of view, **such an initial fallback value for `GetOrSet`, would be great**, since it would allow to fill the gap when the very first attempt to get a value fails, because, e.g. the system called in the factory is not yet available during warmup etc. On the other hand this solution would not disguise later failures of the called system if it's up and running. This is what we need.

By the way: The `CacheExtensions.GetOrCreateAsync<TItem>(IMemoryCache, Object, Func<ICacheEntry,Task<TItem>>)` method supports such different lifetimes indirectly, since you can define the duration separately each time the factory is called. Therefore you do know the results or exceptions of your database calls etc. in the same factory method where you configure the caching options and the problem is solved.

**_Secondly_**, having a initial and subsequent **general** fallback value whenever otherwise an exception would be thrown, could be also beneficial in a pretty exotic case: an expired value could be of little moment compared to a default value.

Note that, for the opposite case (where an expired value makes more sense than a default) the same effect could also be achieved with an unlimited retention period, which is already possible right now, although this repeated fail-safe period prolongation behavior would completely lever out the mechanics of `GetOrSet`...

At the moment, for me personally there is no need for an `GetOrSetOrDefault`, which does not throw any exception at all, but always returns a default value instead.

**Comment by jodydonetti** [comment]
Wow, lots of food for thoughts, thanks!

Let me marinate these ideas and maybe sleep over them and the possible consequences a little more, and I'll come back to you with something.

**Comment by JoeShook** [comment]
This conversation has some similarities to a feature I would like to see.  I am currently working with an old hand rolled cache that has the concept of a NegativeCache feature.  When it is on it nulls are cached.  When it is off nulls are not cached.  

So I would want the Default value cached based on some FusionCacheOptions setting.  But the ability to tune how often a cached null is re-checked would be nice.

**Comment by jodydonetti** [comment]
Hi all, I think I got the right design now.

I'm doing some more tests and perf tuning but in the next few days I'll push the new feature so you can play with it and give me a feedback.

**Comment by jodydonetti** [comment]
Hi @clxx , I've just pushed a couple of new features.


## Added param `failSafeDefaultValue` to `GetOrSet[Async]`

In the commit 1900d960090d69382ed06688270d0d4e9fd6438b I added a new `failSafeDefaultValue` param to the core `GetOrSet` method. This is a way to specify an optional default value to use when fail-safe is enabled and something goes wrong with the factory execution (a timeout, an exception, or anything else).

The type of the param is the new `MaybeValue<TValue>` which is logically similar to a `Nullable<T>`, but which can be used with any type including reference types (somewhat like the maybe/option monad, if you are into functional programming): since it is a struct it does not allocate on the heap, so less heap usage when not used. It also implements implicit conversion to/from `TValue` so you don't have to be explicit when using it.

Of course I added **all the needed overloads** to be able to work with `TimeSpan` instead of explicit options etc, and also the ones needed to **map all the old methods signatures** (without the new param) and related overloads, so everything should - in theory 😅 - compile just like before without any change.


## Added a new `GetOrSet[Async]` method with a direct value (instead of a factory)

Kinda related, some people asked me how to get a value from the cache and, if not there, set a value directly without providing a factory, without the useless lambda allocation and with a less cumbersome way to call it.
So in f7c648033f53630ccbf9fa1b7442303859c2265f I added such new core method (and related overloads for `TimeSpan`, etc).

### Practical example
Before, if we had a value to use when a cache entry was missing, we had to do this:

```csharp
var foo = cache.GetOrSet("foo", _ => 42, TimeSpan.FromMinutes(2));
```

Now instead we can do this:

```csharp
var foo = cache.GetOrSet("foo", 42, TimeSpan.FromMinutes(2));
```

## Documentation
Initially you (@clxx ) said this:

> but from the otherwise excellent documentation and the example code alone it is not clear, how to combine these features

I thought about this a lot and I think that, on top of adding the new `failSafeDefaultValue` param to actually combine factory + default value, I should better clarify in the documentation the difference between `GetOrSet` and `GetOrDefault`.
I was thinking about something like this:

> The `GetOrSet` methods **GET** a value from the cache and, if not there, either calls a **FACTORY** or use the provided **VALUE**, after which it **SET** the new value in the cache and returns it.
> If you provide a factory and enable fail-safe, you can also specify a `failSafeDefaultValue`: if you do so and anything goes wrong with the factory execution you would still be sure the method call does not throw and would **ALWAYS** returns something.

> On the other hand the `GetOrDefault` method **GET** a value from the cache and, if not there, returns a **DEFAULT VALUE** but it will **NEVER** set a new value in the cache. This means any successive call would still **NOT** find the cache entry and maybe call the factory again.

> In short:
> - with `GetOrSet` you **GET** what's in the cache, and maybe something will be **SET** there
> - with `GetOrDefault` you **GET** what's in the cache, or a default value will **JUST BE RETURNED**

What would you think of an explanation like that?


## Closing thoughts
Before publishing a new package version on nuget.org I would like to know what you all think about it ( @clxx @JoeShook @alb-xss ).
Do you see any problems? Do you think the `MaybeValue<TValue>` is a good or bad idea?

**Comment by jodydonetti** [comment]
@JoeShook regarding the "negative cache" concept I think we should open a different issue, since it may be interesting or not but seems to me a cross-cutting concern related to the entire cache and not something specific for this new default values.
Seems fair?

**Comment by JoeShook** [comment]
I think the "negative cache" concept at the moment is something to think about.  It is causing me some friction for a few use cases in an existing project where I have a bunch of unit tests asserting the "negative cache" behavior.  As I replace with FusionCache I am not 100% sold on "negative-cache" being a feature request.  With all the features in FusionCache I just need to keep using it for a while to decide if I need that "negative cache" feature.  I have been in this code base for a solid week and experimenting with it in a project.  I just need to let all this marinate for some time.  

@jodydonetti  thanks for sharing this project with us!  
I will update my metrics PR to this code and try to get some experimenting time with this change.

**Comment by jodydonetti** [comment]
Makes sense, thanks!

**Comment by clxx** [comment]
> ## Added param `failSafeDefaultValue` to `GetOrSet[Async]`
> In the commit [1900d96](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/commit/1900d960090d69382ed06688270d0d4e9fd6438b) I added a new `failSafeDefaultValue` param to the core `GetOrSet` method. This is a way to specify an optional default value to use when fail-safe is enabled and something goes wrong with the factory execution (a timeout, an exception, or anything else).

This sounds great!

> The type of the param is the new `MaybeValue<TValue>` which is logically similar to a `Nullable<T>`, but which can be used with any type including reference types (somewhat like the maybe/option monad, if you are into functional programming): since it is a struct it does not allocate on the heap, so less heap usage when not used. It also implements implicit conversion to/from `TValue` so you don't have to be explicit when using it.

I really like the idea of using such a `MaybeValue<TValue>` here...

> ## Documentation
> Initially you (@clxx ) said this:
> 
> > but from the otherwise excellent documentation and the example code alone it is not clear, how to combine these features
> 
> I thought about this a lot and I think that, on top of adding the new `failSafeDefaultValue` param to actually combine factory + default value, I should better clarify in the documentation the difference between `GetOrSet` and `GetOrDefault`.
> I was thinking about something like this:
> 
> > The `GetOrSet` methods **GET** a value from the cache and, if not there, either calls a **FACTORY** or use the provided **VALUE**, after which it **SET** the new value in the cache and returns it.
> > If you provide a factory and enable fail-safe, you can also specify a `failSafeDefaultValue`: if you do so and anything goes wrong with the factory execution you would still be sure the method call does not throw and would **ALWAYS** returns something.
> 
> > On the other hand the `GetOrDefault` method **GET** a value from the cache and, if not there, returns a **DEFAULT VALUE** but it will **NEVER** set a new value in the cache. This means any successive call would still **NOT** find the cache entry and maybe call the factory again.
> 
> > In short:
> > 
> > * with `GetOrSet` you **GET** what's in the cache, and maybe something will be **SET** there
> > * with `GetOrDefault` you **GET** what's in the cache, or a default value will **JUST BE RETURNED**
> 
> What would you think of an explanation like that?

First of all, thank you, since this makes it much clearer. For me, this explanation is perfect - you may only add one half sentence about the new `failSafeDefaultValue` being "returned whenever anything goes wrong with the factory execution" *and there is no usable fallback entry anymore (initally or due to final expiration).

**Comment by jodydonetti** [comment]
Thanks @clxx , you are in fact right about the half sentence.

**Comment by jodydonetti** [comment]
Also, any opinion on #10 too would be welcome.

**Comment by alb-xss** [comment]
Good work! 👍 I like the idea of setting a value without the memory overhead of a lambda allocation.
On the other hand I'm now a bit skeptical about _**GetOrDefault()**_ and _**TryGet()**_ methods coexistence, I see an overlapping behavior and maybe in the future it will probably be a good idea to merge them in a single method for the sake of semplicity.

**Comment by jodydonetti** [comment]
@alb-xss interesting, why an overlap?

The `TryGet<T>` is the only way to know if something is in the cache or not, because `GetOrDefault<T>` would return the default value of `T` both when the entry is not in the cache and when the calue in the cache was, in fact, the default value of `T`.

Or am I missing something?

**Comment by jodydonetti** [comment]
I've release [v0.1.3](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/releases/tag/v0.1.3) containing this very feature 🎉

**Comment by jodydonetti** [comment]
Also, regarding the documentation: here is a new [dedicated page](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/docs/CoreMethods.md) about core methods.

What do you think @clxx ?

**Comment by clxx** [comment]
This is awesome!
